version: '3.8'

volumes:
  db_data:

secrets:
  db_user:
    external: true
  db_password:
    external: true
  dotenv_key:
    external: true

services:
  app:
    image: tinymosi/price-checker-tg-bot:main
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      TZ: "Asia/Yekaterinburg"
      NODE_ENV: production
      DOTENV_KEY_FILE: dotenv_key
      DB_HOSTNAME: db
      DB_USER_FILE: db_user
      DB_PASSWORD_FILE: db_password
    secrets:
      - dotenv_key
      - db_user
      - db_password
  db:
    hostname: db
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
